export const guestlist = [
    {
        id: 'rsvp',
        rsvp: false,
        type: 'friends',
        size: 0,
        lastname: null,
        names: ['you'],
    },
    {
        id: 'family',
        rsvp: true,
        type: 'family',
        size: 0,
        lastname: null,
        names: [''],
    },
    {
        id: 'shelley-and-tony',
        rsvp: true,
        type: 'family',
        size: 1,
        lastname: 'Day',
        names: ['Shelley', 'Tony'],
    },
    {
        id: 'rebecca-and-josh',
        rsvp: true,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Rebecca', 'Josh'],
    },
    {
        id: 'moose-and-amy',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Moose', 'Amy'],
    },
    {
        id: 'steph-and-chris',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Steph', 'Chris'],
    },
    {
        id: 'mike-and-judy',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: 'Stringer',
        names: ['Mike', 'Judy'],
    },
    {
        id: 'paul',
        rsvp: false,
        type: 'family',
        size: 0,
        lastname: 'Stringer',
        names: ['Paul'],
    },
    {
        id: 'natasha',
        rsvp: true,
        type: 'family',
        size: 0,
        lastname: 'Bale',
        names: ['Natasha'],
    },
    {
        id: 'kirsity',
        rsvp: true,
        type: 'family',
        size: 0,
        lastname: 'Bale',
        names: ['Kirsity'],
    },
    {
        id: 'aunty-jude',
        rsvp: true,
        type: 'family',
        size: 0,
        lastname: null,
        names: ['Aunty Jude'],
    },
    {
        id: 'robyn-and-dave',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Aunty Robyn', 'Uncle Dave'],
    },
    {
        id: 'emma-and-brett',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Emma', 'Brett'],
    },
    {
        id: 'jane-and-jeremy',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Jane', 'Jeremy'],
    },
    {
        id: 'sophie-and-matt',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: 'Lang',
        names: ['Sophie', 'Matt'],
    },
    {
        id: 'jethro-and-nicole',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Riggins',
        names: ['Jethro', 'Nicole'],
    },
    {
        id: 'lathan-and-nikita',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Riggins',
        names: ['Lathan', 'nikita'],
    },
    {
        id: 'teena-lais-and-tess',
        rsvp: false,
        type: 'friends',
        size: 2,
        lastname: 'Morris',
        names: ['Teena', 'Lais', 'Tess'],
    },
    {
        id: 'richard-carissa-and-aria',
        rsvp: false,
        type: 'family',
        size: 2,
        lastname: 'Morris',
        names: ['Uncle Richard', 'Carissa', 'Aria'],
    },
    {
        id: 'roger',
        rsvp: false,
        type: 'family',
        size: 0,
        lastname: null,
        names: ['Uncle Roger'],
    },
    {
        id: 'ann-and-uwe',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Engbers',
        names: ['Ann', 'Uwe'],
    },
    {
        id: 'nicola-and-mike',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Blyth',
        names: ['Nicola', 'Mike'],
    },
    {
        id: 'gabby-and-murray',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Gabby', 'Murray'],
    },
    {
        id: 'nicola',
        rsvp: true,
        type: 'friends',
        size: 0,
        lastname: 'Valk',
        names: ['Nicola'],
    },
    {
        id: 'sara-and-mike',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Allan',
        names: ['Sara', 'Mike'],
    },
    {
        id: 'lisa-and-sas',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Lisa', 'Sas'],
    },
    {
        id: 'pinky-and-gemma',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Pinky', 'Gemma'],
    },
    {
        id: 'beth-and-matt',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Lee',
        names: ['Beth', 'Matt'],
    },
    {
        id: 'bufty-and-vicente',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Bufty', 'Vincente'],
    },
    {
        id: 'daniel-and-teana',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'McKechnie',
        names: ['Daniel', 'Teana'],
    },
    {
        id: 'lauren-and-chris',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Menzies',
        names: ['Lauren', 'Chris'],
    },
    {
        id: 'katrina-and-geoff',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'England',
        names: ['Katrina', 'Geoff'],
    },
    {
        id: 'rach-and-dave',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Rachel', 'Dave'],
    },
    {
        id: 'lilla',
        rsvp: false,
        type: 'friends',
        size: 0,
        lastname: 'Bothma',
        names: ['Lilla'],
    },
    {
        id: 'terri',
        rsvp: true,
        type: 'friends',
        size: 0,
        lastname: 'Hardisty',
        names: ['Terri'],
    },
    {
        id: 'freya',
        rsvp: false,
        type: 'friends',
        size: 0,
        lastname: 'Flockton',
        names: ['Freya'],
    },
    {
        id: 'claire-and-ben',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Langley',
        names: ['Claire', 'Ben'],
    },
    {
        id: 'gay-and-bob',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: 'Harvey',
        names: ['Gay', 'Bob'],
    },
    {
        id: 'bev-and-ian',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: 'Lopdell',
        names: ['Bev', 'Ian'],
    },
    {
        id: 'jill',
        rsvp: true,
        type: 'family',
        size: 0,
        lastname: 'Waru',
        names: ['Jill'],
    },
    {
        id: 'matt-and-mindy',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Windross',
        names: ['Matt', 'Mindy'],
    },
    {
        id: 'brendon-and-amy',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Wallis',
        names: ['Brendon', 'Amy'],
    },
    {
        id: 'cam-and-nina',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Field',
        names: ['Cam', 'Nina'],
    },
    {
        id: 'clint-and-eugenie',
        rsvp: true,
        type: 'friends',
        size: 1,
        lastname: 'Williams',
        names: ['Clint', 'Eugenie'],
    },
    {
        id: 'stacey-and-damien',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: '',
        names: ['Stacey', 'Damien'],
    },
    {
        id: 'kelly-and-jason',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'White',
        names: ['Kelly', 'Jason'],
    },
    {
        id: 'shanee-and-jean',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: 'Ramirez',
        names: ['Shanee', 'Jean'],
    },
    {
        id: 'indran-and-leanne',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Pillay',
        names: ['Indran', 'Leanne'],
    },
    {
        id: 'pratheen',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: null,
        names: ['Pratheen', 'partner'],
    },
    {
        id: 'sarah-and-simon',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Bamfield',
        names: ['Sarah', 'Simon'],
    },
    {
        id: 'lynn-and-david',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Wigg',
        names: ['Lynn', 'David'],
    },
    {
        id: 'lynda-and-peter',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Betts',
        names: ['Lynda', 'Peter'],
    },
    {
        id: 'liz-and-gordon',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: '',
        names: ['Liz', 'Gordon'],
    },
    {
        id: 'richard-and-diana',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Wilks',
        names: ['Richard', 'Diana'],
    },
    {
        id: 'dave-and-margaret',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: '',
        names: ['Dave', 'Margaret'],
    },
    {
        id: 'mary-and-andrew',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Bullivent',
        names: ['Mary', 'Andrew'],
    },
    {
        id: 'nick-and-bernie',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: 'Page',
        names: ['Nick', 'Bernadette'],
    },
    {
        id: 'vic-and-pia',
        rsvp: false,
        type: 'family',
        size: 1,
        lastname: null,
        names: ['Vic', 'Pia'],
    },
    {
        id: 'sarah-and-mimi',
        rsvp: false,
        type: 'friends',
        size: 1,
        lastname: '',
        names: ['Sarah', 'Mimi'],
    },
    {
        id: 'andrew',
        rsvp: false,
        type: 'friends',
        size: 0,
        lastname: 'Kuhn',
        names: ['Andrew'],
    },
];
